---
.travis.yml:
  rubygems_api_key: "XRT6rOJ82TsN+adM6blodauBqAXcBs9MhS0eCkMIuu2UApTxYvU6uQ+1rSzXzgJHoLXAxSWLduvVBQMwbsW6SXkqNph+qVFbP/KZ9cZdctI47IMwqlHw10qv4E4ISCOwnTrWa0hSjaUhMNgX7HsOJuGrJZh++hCYr9rGxmdr6S4="
