language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.5
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: Pz6SGPzNAx26oM0y+z8/Th4tuMkzKt0Mu8B5EusUqt/8LwdKqjdIej9heZQJ/MQuF/9DVeUXw/W5oUP12C34H/iUa6vgt6Q54ByuX2ntHep6jeXsvimyv+oo5V2yHQw7SoTROCWVpMuj1VzbH3/04e+go5GU0ixttVHj/3q9dPc=
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
